version: '3.8'
services:
  
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    hostname: mysql-container
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: mh22xx01
      MYSQL_DATABASE: easy-bank
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - easy-bank-network
    volumes:
      - mysql-data-container:/var/lib/mysql

  keycloak:
    container_name: keyCloak-container
    image: quay.io/keycloak/keycloak:latest
    hostname: keyCloak-container
    command:
      - start-dev --http-port 8081
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8081:8081'
    expose:
      - 8081
    networks:
      - easy-bank-network

volumes:
  mysql-data-container:

networks:
  easy-bank-network:
    driver: bridge