spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy-bank?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    username: root
    password: mh22xx01
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
