spring:
  datasource:
    url: jdbc:mysql://easy-bank.c89icaq4xhv5.us-east-1.rds.amazonaws.com/easy-bank
    username: root
    password: mh22xx01
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
